**/.env
**/.git
**/.gitattributes
**/.gitignore
**/.vs
**/.vscode
**/*.*proj.user
**/*.dbmdl
**/*.jfm

**/bin
**/obj
**/charts
**/secrets.dev.yaml
**/values.dev.yaml

CONTRIBUTING.md
LICENSE.md
README.md
