Table "dbo"."Genre" {
    "Id" uniqueidentifier [primary key, not null, default: `NEWID()`]
    "Name" nvarchar(256) [not null]
    "Description" nvarchar(2048) [null]
    "SystemEntity" bit [not null]
    "Enabled" bit [not null]
    "CreatedOn" datetimeoffset [not null, default: `SYSDATETIMEOFFSET()`]
    "UpdatedOn" datetimeoffset [not null, default: `SYSDATETIMEOFFSET()`]
}

Table "dbo"."GenreRelationship" {
    "GenreId" uniqueidentifier [primary key, not null]
    "DependentGenreId" uniqueidentifier [primary key, not null]
    "Name" nvarchar(256) [not null]
    "Description" nvarchar(2048) [null]
    "Order" int [not null]

    Indexes {
        "GenreId" [name: "IX_GenreRelationship_GenreId"]
        "DependentGenreId" [name: "IX_GenreRelationship_DependentGenreId"]
        ("GenreId", "Order") [name: "UIX_GenreRelationship_GenreId_Order", unique]
    }
}

Ref "FK_GenreRelationship_Genre_GenreId" {
    "dbo"."GenreRelationship"."GenreId" > "dbo"."Genre"."Id"
}

Ref "FK_GenreRelationship_Genre_DependentGenreId" {
    "dbo"."GenreRelationship"."DependentGenreId" > "dbo"."Genre"."Id"
}


Table "dbo"."Artist" {
    "Id" uniqueidentifier [primary key, not null, default: `NEWID()`]
    "Name" nvarchar(256) [not null]
    "Description" nvarchar(2048) [null]
    "DisambiguationText" nvarchar(2048) [null]
    "SystemEntity" bit [not null]
    "Enabled" bit [not null]
    "CreatedOn" datetimeoffset [not null, default: `SYSDATETIMEOFFSET()`]
    "UpdatedOn" datetimeoffset [not null, default: `SYSDATETIMEOFFSET()`]
}

Table "dbo"."ArtistRelationship" {
    "ArtistId" uniqueidentifier [primary key, not null]
    "DependentArtistId" uniqueidentifier [primary key, not null]
    "Name" nvarchar(256) [not null]
    "Description" nvarchar(2048) [null]
    "Order" int [not null]

    Indexes {
        "ArtistId" [name: "IX_ArtistRelationship_ArtistId"]
        "DependentArtistId" [name: "IX_ArtistRelationship_DependentArtistId"]
        ("ArtistId", "Order") [name: "UIX_ArtistRelationship_ArtistId_Order", unique]
    }
}

Ref "FK_ArtistRelationship_Artist_ArtistId" {
    "dbo"."ArtistRelationship"."ArtistId" > "dbo"."Artist"."Id"
}

Ref "FK_ArtistRelationship_Artist_DependentArtistId" {
    "dbo"."ArtistRelationship"."DependentArtistId" > "dbo"."Artist"."Id"
}

Table "dbo"."ArtistGenre" {
    "ArtistId" uniqueidentifier [primary key, not null]
    "GenreId" uniqueidentifier [primary key, not null]
    "Order" int [not null]

    Indexes {
        "ArtistId" [name: "IX_ArtistGenre_ArtistId"]
        "GenreId" [name: "IX_ArtistGenre_GenreId"]
        ("ArtistId", "Order") [name: "UIX_ArtistGenre_ArtistId_Order", unique]
    }
}

Ref "FK_ArtistGenre_Artist_ArtistId" {
    "dbo"."ArtistGenre"."ArtistId" > "dbo"."Artist"."Id"
}

Ref "FK_ArtistGenre_Genre_GenreId" {
    "dbo"."ArtistGenre"."GenreId" > "dbo"."Genre"."Id"
}


Table "dbo"."Product" {
    "Id" uniqueidentifier [primary key, not null, default: `NEWID()`]
    "Title" nvarchar(256) [not null]
    "Description" nvarchar(2048) [null]
    "DisambiguationText" nvarchar(2048) [null]
    "ReleasedOn" date [not null]
    "ReleasedOnYearOnly" bit [not null]
    "SystemEntity" bit [not null]
    "Enabled" bit [not null]
    "CreatedOn" datetimeoffset [not null, default: `SYSDATETIMEOFFSET()`]
    "UpdatedOn" datetimeoffset [not null, default: `SYSDATETIMEOFFSET()`]
}

Table "dbo"."ProductRelationship" {
    "ProductId" uniqueidentifier [primary key, not null]
    "DependentProductId" uniqueidentifier [primary key, not null]
    "Name" nvarchar(256) [not null]
    "Description" nvarchar(2048) [null]
    "Order" int [not null]

    Indexes {
        "ProductId" [name: "IX_ProductRelationship_ProductId"]
        "DependentProductId" [name: "IX_ProductRelationship_DependentProductId"]
        ("ProductId", "Order") [name: "UIX_ProductRelationship_ProductId_Order", unique]
    }
}

Ref "FK_ProductRelationship_Product_ProductId" {
    "dbo"."ProductRelationship"."ProductId" > "dbo"."Product"."Id"
}

Ref "FK_ProductRelationship_Product_DependentProductId" {
    "dbo"."ProductRelationship"."DependentProductId" > "dbo"."Product"."Id"
}


Table "dbo"."Work" {
    "Id" uniqueidentifier [primary key, not null, default: `NEWID()`]
    "Title" nvarchar(256) [not null]
    "Description" nvarchar(2048) [null]
    "DisambiguationText" nvarchar(2048) [null]
    "InternationalStandardMusicalWorkCode" nvarchar(32) [null]
    "ReleasedOn" date [not null]
    "ReleasedOnYearOnly" bit [not null]
    "SystemEntity" bit [not null]
    "Enabled" bit [not null]
    "CreatedOn" datetimeoffset [not null, default: `SYSDATETIMEOFFSET()`]
    "UpdatedOn" datetimeoffset [not null, default: `SYSDATETIMEOFFSET()`]

    Indexes {
        "InternationalStandardMusicalWorkCode" [name: "IX_Work_InternationalStandardMusicalWorkCode"]
    }
}

Table "dbo"."WorkRelationship" {
    "WorkId" uniqueidentifier [primary key, not null]
    "DependentWorkId" uniqueidentifier [primary key, not null]
    "Name" nvarchar(256) [not null]
    "Description" nvarchar(2048) [null]
    "Order" int [not null]

    Indexes {
        "WorkId" [name: "IX_WorkRelationship_WorkId"]
        "DependentWorkId" [name: "IX_WorkRelationship_DependentWorkId"]
        ("WorkId", "Order") [name: "UIX_WorkRelationship_WorkId_Order", unique]
    }
}

Ref "FK_WorkRelationship_Work_WorkId" {
    "dbo"."WorkRelationship"."WorkId" > "dbo"."Work"."Id"
}

Ref "FK_WorkRelationship_Work_DependentWorkId" {
    "dbo"."WorkRelationship"."DependentWorkId" > "dbo"."Work"."Id"
}

Table "dbo"."WorkArtist" {
    "WorkId" uniqueidentifier [primary key, not null]
    "ArtistId" uniqueidentifier [primary key, not null]
    "Order" int [not null]

    Indexes {
        "WorkId" [name: "IX_WorkArtist_WorkId"]
        "ArtistId" [name: "IX_WorkArtist_ArtistId"]
        ("WorkId", "Order") [name: "UIX_WorkArtist_WorkId_Order", unique]
    }
}

Ref "FK_WorkArtist_Work_WorkId" {
    "dbo"."WorkArtist"."WorkId" > "dbo"."Work"."Id"
}

Ref "FK_WorkArtist_Artist_ArtistId" {
    "dbo"."WorkArtist"."ArtistId" > "dbo"."Artist"."Id"
}

Table "dbo"."WorkFeaturedArtist" {
    "WorkId" uniqueidentifier [primary key, not null]
    "ArtistId" uniqueidentifier [primary key, not null]
    "Order" int [not null]

    Indexes {
        "WorkId" [name: "IX_WorkFeaturedArtist_WorkId"]
        "ArtistId" [name: "IX_WorkFeaturedArtist_ArtistId"]
        ("WorkId", "Order") [name: "UIX_WorkFeaturedArtist_WorkId_Order", unique]
    }
}

Ref "FK_WorkFeaturedArtist_Work_WorkId" {
    "dbo"."WorkFeaturedArtist"."WorkId" > "dbo"."Work"."Id"
}

Ref "FK_WorkFeaturedArtist_Artist_ArtistId" {
    "dbo"."WorkFeaturedArtist"."ArtistId" > "dbo"."Artist"."Id"
}

Table "dbo"."WorkPerformer" {
    "WorkId" uniqueidentifier [primary key, not null]
    "ArtistId" uniqueidentifier [primary key, not null]
    "Order" int [not null]

    Indexes {
        "WorkId" [name: "IX_WorkPerformer_WorkId"]
        "ArtistId" [name: "IX_WorkPerformer_ArtistId"]
        ("WorkId", "Order") [name: "UIX_WorkPerformer_WorkId_Order", unique]
    }
}

Ref "FK_WorkPerformer_Work_WorkId" {
    "dbo"."WorkPerformer"."WorkId" > "dbo"."Work"."Id"
}

Ref "FK_WorkPerformer_Artist_ArtistId" {
    "dbo"."WorkPerformer"."ArtistId" > "dbo"."Artist"."Id"
}

Table "dbo"."WorkComposer" {
    "WorkId" uniqueidentifier [primary key, not null]
    "ArtistId" uniqueidentifier [primary key, not null]
    "Order" int [not null]

    Indexes {
        "WorkId" [name: "IX_WorkComposer_WorkId"]
        "ArtistId" [name: "IX_WorkComposer_ArtistId"]
        ("WorkId", "Order") [name: "UIX_WorkComposer_WorkId_Order", unique]
    }
}

Ref "FK_WorkComposer_Work_WorkId" {
    "dbo"."WorkComposer"."WorkId" > "dbo"."Work"."Id"
}

Ref "FK_WorkComposer_Artist_ArtistId" {
    "dbo"."WorkComposer"."ArtistId" > "dbo"."Artist"."Id"
}

Table "dbo"."WorkGenre" {
    "WorkId" uniqueidentifier [primary key, not null]
    "GenreId" uniqueidentifier [primary key, not null]
    "Order" int [not null]

    Indexes {
        "WorkId" [name: "IX_WorkGenre_WorkId"]
        "GenreId" [name: "IX_WorkGenre_GenreId"]
        ("WorkId", "Order") [name: "UIX_WorkGenre_WorkId_Order", unique]
    }
}

Ref "FK_WorkGenre_Work_WorkId" {
    "dbo"."WorkGenre"."WorkId" > "dbo"."Work"."Id"
}

Ref "FK_WorkGenre_Genre_GenreId" {
    "dbo"."WorkGenre"."GenreId" > "dbo"."Genre"."Id"
}

Table "dbo"."WorkToProductRelationship" {
    "WorkId" uniqueidentifier [primary key, not null]
    "ProductId" uniqueidentifier [primary key, not null]
    "Name" nvarchar(256) [not null]
    "Description" nvarchar(2048) [null]
    "Order" int [not null]
    "ReferenceOrder" int [not null]

    Indexes {
        "WorkId" [name: "IX_WorkToProductRelationship_WorkId"]
        "ProductId" [name: "IX_WorkToProductRelationship_ProductId"]
        ("WorkId", "Order") [name: "UIX_WorkToProductRelationship_WorkId_Order", unique]
        ("ProductId", "ReferenceOrder") [name: "UIX_WorkToProductRelationship_ProductId_ReferenceOrder", unique]
    }
}

Ref "FK_WorkToProductRelationship_Work_WorkId" {
    "dbo"."WorkToProductRelationship"."WorkId" > "dbo"."Work"."Id"
}

Ref "FK_WorkToProductRelationship_Product_ProductId" {
    "dbo"."WorkToProductRelationship"."ProductId" > "dbo"."Product"."Id"
}


Table "dbo"."ReleaseGroup" {
    "Id" uniqueidentifier [primary key, not null, default: `NEWID()`]
    "Title" nvarchar(256) [not null]
    "Description" nvarchar(2048) [null]
    "DisambiguationText" nvarchar(2048) [null]
    "Enabled" bit [not null]
    "CreatedOn" datetimeoffset [not null, default: `SYSDATETIMEOFFSET()`]
    "UpdatedOn" datetimeoffset [not null, default: `SYSDATETIMEOFFSET()`]
}

Table "dbo"."ReleaseGroupRelationship" {
    "ReleaseGroupId" uniqueidentifier [primary key, not null]
    "DependentReleaseGroupId" uniqueidentifier [primary key, not null]
    "Name" nvarchar(256) [not null]
    "Description" nvarchar(2048) [null]
    "Order" int [not null]

    Indexes {
        "ReleaseGroupId" [name: "IX_ReleaseGroupRelationship_ReleaseGroupId"]
        "DependentReleaseGroupId" [name: "IX_ReleaseGroupRelationship_DependentReleaseGroupId"]
        ("ReleaseGroupId", "Order") [name: "UIX_ReleaseGroupRelationship_ReleaseGroupId_Order", unique]
    }
}

Ref "FK_ReleaseGroupRelationship_ReleaseGroup_ReleaseGroupId" {
    "dbo"."ReleaseGroupRelationship"."ReleaseGroupId" > "dbo"."ReleaseGroup"."Id"
}

Ref "FK_ReleaseGroupRelationship_ReleaseGroup_DependentReleaseGroupId" {
    "dbo"."ReleaseGroupRelationship"."DependentReleaseGroupId" > "dbo"."ReleaseGroup"."Id"
}


Table "dbo"."Release" {
    "Id" uniqueidentifier [primary key, not null, default: `NEWID()`]
    "Title" nvarchar(256) [not null]
    "Description" nvarchar(2048) [null]
    "DisambiguationText" nvarchar(2048) [null]
    "Barcode" nvarchar(32) [null]
    "CatalogNumber" nvarchar(32) [null]
    "MediaFormat" nvarchar(256) [null]
    "PublishFormat" nvarchar(256) [null]
    "ReleasedOn" date [not null]
    "ReleasedOnYearOnly" bit [not null]
    "Enabled" bit [not null]
    "CreatedOn" datetimeoffset [not null, default: `SYSDATETIMEOFFSET()`]
    "UpdatedOn" datetimeoffset [not null, default: `SYSDATETIMEOFFSET()`]

    Indexes {
        "Barcode" [name: "IX_Release_Barcode"]
        "CatalogNumber" [name: "IX_Release_CatalogNumber"]
    }
}

Table "dbo"."ReleaseRelationship" {
    "ReleaseId" uniqueidentifier [primary key, not null]
    "DependentReleaseId" uniqueidentifier [primary key, not null]
    "Name" nvarchar(256) [not null]
    "Description" nvarchar(2048) [null]
    "Order" int [not null]

    Indexes {
        "ReleaseId" [name: "IX_ReleaseRelationship_ReleaseId"]
        "DependentReleaseId" [name: "IX_ReleaseRelationship_DependentReleaseId"]
        ("ReleaseId", "Order") [name: "UIX_ReleaseRelationship_ReleaseId_Order", unique]
    }
}

Ref "FK_ReleaseRelationship_Release_ReleaseId" {
    "dbo"."ReleaseRelationship"."ReleaseId" > "dbo"."Release"."Id"
}

Ref "FK_ReleaseRelationship_Release_DependentReleaseId" {
    "dbo"."ReleaseRelationship"."DependentReleaseId" > "dbo"."Release"."Id"
}

Table "dbo"."ReleaseArtist" {
    "ReleaseId" uniqueidentifier [primary key, not null]
    "ArtistId" uniqueidentifier [primary key, not null]
    "Order" int [not null]

    Indexes {
        "ReleaseId" [name: "IX_ReleaseArtist_ReleaseId"]
        "ArtistId" [name: "IX_ReleaseArtist_ArtistId"]
        ("ReleaseId", "Order") [name: "UIX_ReleaseArtist_ReleaseId_Order", unique]
    }
}

Ref "FK_ReleaseArtist_Release_ReleaseId" {
    "dbo"."ReleaseArtist"."ReleaseId" > "dbo"."Release"."Id"
}

Ref "FK_ReleaseArtist_Artist_ArtistId" {
    "dbo"."ReleaseArtist"."ArtistId" > "dbo"."Artist"."Id"
}

Table "dbo"."ReleaseFeaturedArtist" {
    "ReleaseId" uniqueidentifier [primary key, not null]
    "ArtistId" uniqueidentifier [primary key, not null]
    "Order" int [not null]

    Indexes {
        "ReleaseId" [name: "IX_ReleaseFeaturedArtist_ReleaseId"]
        "ArtistId" [name: "IX_ReleaseFeaturedArtist_ArtistId"]
        ("ReleaseId", "Order") [name: "UIX_ReleaseFeaturedArtist_ReleaseId_Order", unique]
    }
}

Ref "FK_ReleaseFeaturedArtist_Release_ReleaseId" {
    "dbo"."ReleaseFeaturedArtist"."ReleaseId" > "dbo"."Release"."Id"
}

Ref "FK_ReleaseFeaturedArtist_Artist_ArtistId" {
    "dbo"."ReleaseFeaturedArtist"."ArtistId" > "dbo"."Artist"."Id"
}

Table "dbo"."ReleasePerformer" {
    "ReleaseId" uniqueidentifier [primary key, not null]
    "ArtistId" uniqueidentifier [primary key, not null]
    "Order" int [not null]

    Indexes {
        "ReleaseId" [name: "IX_ReleasePerformer_ReleaseId"]
        "ArtistId" [name: "IX_ReleasePerformer_ArtistId"]
        ("ReleaseId", "Order") [name: "UIX_ReleasePerformer_ReleaseId_Order", unique]
    }
}

Ref "FK_ReleasePerformer_Release_ReleaseId" {
    "dbo"."ReleasePerformer"."ReleaseId" > "dbo"."Release"."Id"
}

Ref "FK_ReleasePerformer_Artist_ArtistId" {
    "dbo"."ReleasePerformer"."ArtistId" > "dbo"."Artist"."Id"
}

Table "dbo"."ReleaseComposer" {
    "ReleaseId" uniqueidentifier [primary key, not null]
    "ArtistId" uniqueidentifier [primary key, not null]
    "Order" int [not null]

    Indexes {
        "ReleaseId" [name: "IX_ReleaseComposer_ReleaseId"]
        "ArtistId" [name: "IX_ReleaseComposer_ArtistId"]
        ("ReleaseId", "Order") [name: "UIX_ReleaseComposer_ReleaseId_Order", unique]
    }
}

Ref "FK_ReleaseComposer_Release_ReleaseId" {
    "dbo"."ReleaseComposer"."ReleaseId" > "dbo"."Release"."Id"
}

Ref "FK_ReleaseComposer_Artist_ArtistId" {
    "dbo"."ReleaseComposer"."ArtistId" > "dbo"."Artist"."Id"
}

Table "dbo"."ReleaseGenre" {
    "ReleaseId" uniqueidentifier [primary key, not null]
    "GenreId" uniqueidentifier [primary key, not null]
    "Order" int [not null]

    Indexes {
        "ReleaseId" [name: "IX_ReleaseGenre_ReleaseId"]
        "GenreId" [name: "IX_ReleaseGenre_GenreId"]
        ("ReleaseId", "Order") [name: "UIX_ReleaseGenre_ReleaseId_Order", unique]
    }
}

Ref "FK_ReleaseGenre_Release_ReleaseId" {
    "dbo"."ReleaseGenre"."ReleaseId" > "dbo"."Release"."Id"
}

Ref "FK_ReleaseGenre_Genre_GenreId" {
    "dbo"."ReleaseGenre"."GenreId" > "dbo"."Genre"."Id"
}

Table "dbo"."ReleaseToProductRelationship" {
    "ReleaseId" uniqueidentifier [primary key, not null]
    "ProductId" uniqueidentifier [primary key, not null]
    "Order" int [not null]
    "ReferenceOrder" int [not null]

    Indexes {
        "ReleaseId" [name: "IX_ReleaseToProductRelationship_ReleaseId"]
        "ProductId" [name: "IX_ReleaseToProductRelationship_ProductId"]
        ("ReleaseId", "Order") [name: "UIX_ReleaseToProductRelationship_ReleaseId_Order", unique]
        ("ProductId", "ReferenceOrder") [name: "UIX_ReleaseToProductRelationship_ProductId_ReferenceOrder", unique]
    }
}

Ref "FK_ReleaseToProductRelationship_Release_ReleaseId" {
    "dbo"."ReleaseToProductRelationship"."ReleaseId" > "dbo"."Release"."Id"
}

Ref "FK_ReleaseToProductRelationship_Product_ProductId" {
    "dbo"."ReleaseToProductRelationship"."ProductId" > "dbo"."Product"."Id"
}

Table "dbo"."ReleaseToReleaseGroupRelationship" {
    "ReleaseId" uniqueidentifier [primary key, not null]
    "ReleaseGroupId" uniqueidentifier [primary key, not null]
    "Order" int [not null]
    "ReferenceOrder" int [not null]

    Indexes {
        "ReleaseId" [name: "IX_ReleaseToReleaseGroupRelationship_ReleaseId"]
        "ReleaseGroupId" [name: "IX_ReleaseToReleaseGroupRelationship_ReleaseGroupId"]
        ("ReleaseId", "Order") [name: "UIX_ReleaseToReleaseGroupRelationship_ReleaseId_Order", unique]
        ("ReleaseGroupId", "ReferenceOrder") [name: "UIX_ReleaseToReleaseGroupRelationship_ReleaseGroupId_ReferenceOrder", unique]
    }
}

Ref "FK_ReleaseToReleaseGroupRelationship_Release_ReleaseId" {
    "dbo"."ReleaseToReleaseGroupRelationship"."ReleaseId" > "dbo"."Release"."Id"
}

Ref "FK_ReleaseToReleaseGroupRelationship_ReleaseGroup_ReleaseGroupId" {
    "dbo"."ReleaseToReleaseGroupRelationship"."ReleaseGroupId" > "dbo"."ReleaseGroup"."Id"
}


Table "dbo"."ReleaseMedia" {
    "MediaNumber" tinyint [primary key, not null]
    "ReleaseId" uniqueidentifier [primary key, not null]
    "Title" nvarchar(256) [not null]
    "Description" nvarchar(2048) [null]
    "DisambiguationText" nvarchar(2048) [null]
    "CatalogNumber" nvarchar(32) [null]
    "MediaFormat" nvarchar(256) [null]
    "TableOfContentsChecksum" nvarchar(64) [null]
    "TableOfContentsChecksumLong" nvarchar(64) [null]

    Indexes {
        "ReleaseId" [name: "IX_ReleaseMedia_ReleaseId"]
        "CatalogNumber" [name: "IX_ReleaseMedia_CatalogNumber"]
        "TableOfContentsChecksum" [name: "IX_ReleaseMedia_TableOfContentsChecksum"]
        "TableOfContentsChecksumLong" [name: "IX_ReleaseMedia_TableOfContentsChecksumLong"]
    }
}

Ref "FK_ReleaseMedia_Release_ReleaseId" {
    "dbo"."ReleaseMedia"."ReleaseId" > "dbo"."Release"."Id"
}

Table "dbo"."ReleaseMediaToProductRelationship" {
    "MediaNumber" tinyint [primary key, not null]
    "ReleaseId" uniqueidentifier [primary key, not null]
    "ProductId" uniqueidentifier [primary key, not null]
    "Order" int [not null]
    "ReferenceOrder" int [not null]

    Indexes {
        ("MediaNumber", "ReleaseId") [name: "IX_ReleaseMediaToProductRelationship_MediaNumber_ReleaseId"]
        "ProductId" [name: "IX_ReleaseMediaToProductRelationship_ProductId"]
        ("MediaNumber", "ReleaseId", "Order") [name: "UIX_ReleaseMediaToProductRelationship_MediaNumber_ReleaseId_Order", unique]
        ("ProductId", "ReferenceOrder") [name: "UIX_ReleaseMediaToProductRelationship_ProductId_ReferenceOrder", unique]
    }
}

Ref "FK_ReleaseMediaToProductRelationship_MediaNumber_ReleaseId" {
    "dbo"."ReleaseMediaToProductRelationship".("MediaNumber", "ReleaseId") > "dbo"."ReleaseMedia".("MediaNumber", "ReleaseId")
}

Ref "FK_ReleaseMediaToProductRelationship_Product_ProductId" {
    "dbo"."ReleaseMediaToProductRelationship"."ProductId" > "dbo"."Product"."Id"
}


Table "dbo"."ReleaseTrack" {
    "TrackNumber" tinyint [primary key, not null]
    "MediaNumber" tinyint [primary key, not null]
    "ReleaseId" uniqueidentifier [primary key, not null]
    "Title" nvarchar(256) [not null]
    "Description" nvarchar(2048) [null]
    "DisambiguationText" nvarchar(2048) [null]
    "InternationalStandardRecordingCode" nvarchar(32) [null]

    Indexes {
        "ReleaseId" [name: "IX_ReleaseTrack_ReleaseId"]
        ("MediaNumber", "ReleaseId") [name: "IX_ReleaseTrack_MediaNumber_ReleaseId"]
        "InternationalStandardRecordingCode" [name: "IX_ReleaseTrack_InternationalStandardRecordingCode"]
    }
}

Ref "FK_ReleaseTrack_ReleaseMedia_MediaNumber_ReleaseId" {
    "dbo"."ReleaseTrack".("MediaNumber", "ReleaseId") > "dbo"."ReleaseMedia".("MediaNumber", "ReleaseId")
}

Table "dbo"."ReleaseTrackArtist" {
    "TrackNumber" tinyint [primary key, not null]
    "MediaNumber" tinyint [primary key, not null]
    "ReleaseId" uniqueidentifier [primary key, not null]
    "ArtistId" uniqueidentifier [primary key, not null]
    "Order" int [not null]

    Indexes {
        ("TrackNumber", "MediaNumber", "ReleaseId") [name: "IX_ReleaseTrackArtist_TrackNumber_MediaNumber_ReleaseId"]
        "ArtistId" [name: "IX_ReleaseTrackArtist_ArtistId"]
        ("TrackNumber", "MediaNumber", "ReleaseId", "Order") [name: "UIX_ReleaseTrackArtist_TrackNumber_MediaNumber_ReleaseId_Order", unique]
    }
}

Ref "FK_ReleaseTrackArtist_ReleaseTrack_TrackNumber_MediaNumber_ReleaseId" {
    "dbo"."ReleaseTrackArtist".("TrackNumber", "MediaNumber", "ReleaseId") > "dbo"."ReleaseTrack".("TrackNumber", "MediaNumber", "ReleaseId")
}

Ref "FK_ReleaseTrackArtist_Artist_ArtistId" {
    "dbo"."ReleaseTrackArtist"."ArtistId" > "dbo"."Artist"."Id"
}

Table "dbo"."ReleaseTrackFeaturedArtist" {
    "TrackNumber" tinyint [primary key, not null]
    "MediaNumber" tinyint [primary key, not null]
    "ReleaseId" uniqueidentifier [primary key, not null]
    "ArtistId" uniqueidentifier [primary key, not null]
    "Order" int [not null]

    Indexes {
        ("TrackNumber", "MediaNumber", "ReleaseId") [name: "IX_ReleaseTrackFeaturedArtist_TrackNumber_MediaNumber_ReleaseId"]
        "ArtistId" [name: "IX_ReleaseTrackFeaturedArtist_ArtistId"]
        ("TrackNumber", "MediaNumber", "ReleaseId", "Order") [name: "UIX_ReleaseTrackFeaturedArtist_TrackNumber_MediaNumber_ReleaseId_Order", unique]
    }
}

Ref "FK_ReleaseTrackFeaturedArtist_ReleaseTrack_TrackNumber_MediaNumber_ReleaseId" {
    "dbo"."ReleaseTrackFeaturedArtist".("TrackNumber", "MediaNumber", "ReleaseId") > "dbo"."ReleaseTrack".("TrackNumber", "MediaNumber", "ReleaseId")
}

Ref "FK_ReleaseTrackFeaturedArtist_Artist_ArtistId" {
    "dbo"."ReleaseTrackFeaturedArtist"."ArtistId" > "dbo"."Artist"."Id"
}

Table "dbo"."ReleaseTrackPerformer" {
    "TrackNumber" tinyint [primary key, not null]
    "MediaNumber" tinyint [primary key, not null]
    "ReleaseId" uniqueidentifier [primary key, not null]
    "ArtistId" uniqueidentifier [primary key, not null]
    "Order" int [not null]

    Indexes {
        ("TrackNumber", "MediaNumber", "ReleaseId") [name: "IX_ReleaseTrackPerformer_TrackNumber_MediaNumber_ReleaseId"]
        "ArtistId" [name: "IX_ReleaseTrackPerformer_ArtistId"]
        ("TrackNumber", "MediaNumber", "ReleaseId", "Order") [name: "UIX_ReleaseTrackPerformer_TrackNumber_MediaNumber_ReleaseId_Order", unique]
    }
}

Ref "FK_ReleaseTrackPerformer_ReleaseTrack_TrackNumber_MediaNumber_ReleaseId" {
    "dbo"."ReleaseTrackPerformer".("TrackNumber", "MediaNumber", "ReleaseId") > "dbo"."ReleaseTrack".("TrackNumber", "MediaNumber", "ReleaseId")
}

Ref "FK_ReleaseTrackPerformer_Artist_ArtistId" {
    "dbo"."ReleaseTrackPerformer"."ArtistId" > "dbo"."Artist"."Id"
}

Table "dbo"."ReleaseTrackComposer" {
    "TrackNumber" tinyint [primary key, not null]
    "MediaNumber" tinyint [primary key, not null]
    "ReleaseId" uniqueidentifier [primary key, not null]
    "ArtistId" uniqueidentifier [primary key, not null]
    "Order" int [not null]

    Indexes {
        ("TrackNumber", "MediaNumber", "ReleaseId") [name: "IX_ReleaseTrackComposer_TrackNumber_MediaNumber_ReleaseId"]
        "ArtistId" [name: "IX_ReleaseTrackComposer_ArtistId"]
        ("TrackNumber", "MediaNumber", "ReleaseId", "Order") [name: "UIX_ReleaseTrackComposer_TrackNumber_MediaNumber_ReleaseId_Order", unique]
    }
}

Ref "FK_ReleaseTrackComposer_ReleaseTrack_TrackNumber_MediaNumber_ReleaseId" {
    "dbo"."ReleaseTrackComposer".("TrackNumber", "MediaNumber", "ReleaseId") > "dbo"."ReleaseTrack".("TrackNumber", "MediaNumber", "ReleaseId")
}

Ref "FK_ReleaseTrackComposer_Artist_ArtistId" {
    "dbo"."ReleaseTrackComposer"."ArtistId" > "dbo"."Artist"."Id"
}

Table "dbo"."ReleaseTrackGenre" {
    "TrackNumber" tinyint [primary key, not null]
    "MediaNumber" tinyint [primary key, not null]
    "ReleaseId" uniqueidentifier [primary key, not null]
    "GenreId" uniqueidentifier [primary key, not null]
    "Order" int [not null]

    Indexes {
        ("TrackNumber", "MediaNumber", "ReleaseId") [name: "IX_ReleaseTrackGenre_TrackNumber_MediaNumber_ReleaseId"]
        "GenreId" [name: "IX_ReleaseTrackGenre_GenreId"]
        ("TrackNumber", "MediaNumber", "ReleaseId", "Order") [name: "UIX_ReleaseTrackGenre_TrackNumber_MediaNumber_ReleaseId_Order", unique]
    }
}

Ref "FK_ReleaseTrackGenre_ReleaseTrack_TrackNumber_MediaNumber_ReleaseId" {
    "dbo"."ReleaseTrackGenre".("TrackNumber", "MediaNumber", "ReleaseId") > "dbo"."ReleaseTrack".("TrackNumber", "MediaNumber", "ReleaseId")
}

Ref "FK_ReleaseTrackGenre_Genre_GenreId" {
    "dbo"."ReleaseTrackGenre"."GenreId" > "dbo"."Genre"."Id"
}

Table "dbo"."ReleaseTrackToProductRelationship" {
    "TrackNumber" tinyint [primary key, not null]
    "MediaNumber" tinyint [primary key, not null]
    "ReleaseId" uniqueidentifier [primary key, not null]
    "ProductId" uniqueidentifier [primary key, not null]
    "Order" int [not null]
    "ReferenceOrder" int [not null]

    Indexes {
        ("TrackNumber", "MediaNumber", "ReleaseId") [name: "IX_ReleaseTrackToProductRelationship_TrackNumber_MediaNumber_ReleaseId"]
        "ProductId" [name: "IX_ReleaseTrackToProductRelationship_ProductId"]
        ("TrackNumber", "MediaNumber", "ReleaseId", "Order") [name: "UIX_ReleaseTrackToProductRelationship_TrackNumber_MediaNumber_ReleaseId_Order", unique]
        ("ProductId", "ReferenceOrder") [name: "UIX_ReleaseTrackToProductRelationship_ProductId_ReferenceOrder", unique]
    }
}

Ref "FK_ReleaseTrackToProductRelationship_ReleaseTrack_TrackNumber_MediaNumber_ReleaseId" {
    "dbo"."ReleaseTrackToProductRelationship".("TrackNumber", "MediaNumber", "ReleaseId") > "dbo"."ReleaseTrack".("TrackNumber", "MediaNumber", "ReleaseId")
}

Ref "FK_ReleaseTrackToProductRelationship_Product_ProductId" {
    "dbo"."ReleaseTrackToProductRelationship"."ProductId" > "dbo"."Product"."Id"
}

Table "dbo"."ReleaseTrackToWorkRelationship" {
    "TrackNumber" tinyint [primary key, not null]
    "MediaNumber" tinyint [primary key, not null]
    "ReleaseId" uniqueidentifier [primary key, not null]
    "WorkId" uniqueidentifier [primary key, not null]
    "Order" int [not null]
    "ReferenceOrder" int [not null]

    Indexes {
        ("TrackNumber", "MediaNumber", "ReleaseId") [name: "IX_ReleaseTrackToWorkRelationship_TrackNumber_MediaNumber_ReleaseId"]
        "WorkId" [name: "IX_ReleaseTrackToWorkRelationship_WorkId"]
        ("TrackNumber", "MediaNumber", "ReleaseId", "Order") [name: "UIX_ReleaseTrackToWorkRelationship_TrackNumber_MediaNumber_ReleaseId_Order", unique]
        ("WorkId", "ReferenceOrder") [name: "UIX_ReleaseTrackToWorkRelationship_WorkId_ReferenceOrder", unique]
    }
}

Ref "FK_ReleaseTrackToWorkRelationship_ReleaseTrack_TrackNumber_MediaNumber_ReleaseId" {
    "dbo"."ReleaseTrackToWorkRelationship".("TrackNumber", "MediaNumber", "ReleaseId") > "dbo"."ReleaseTrack".("TrackNumber", "MediaNumber", "ReleaseId")
}

Ref "FK_ReleaseTrackToWorkRelationship_Work_WorkId" {
    "dbo"."ReleaseTrackToWorkRelationship"."WorkId" > "dbo"."Work"."Id"
}
