Table "dbo"."Genre" {
    "Id" uniqueidentifier [primary key, not null, default: `NEWID()`]
    "Name" nvarchar(256) [not null]
    "Description" nvarchar(2048) [null]
    "SystemEntity" bit [not null]
    "Enabled" bit [not null]
    "CreatedOn" datetimeoffset [not null, default: `SYSDATETIMEOFFSET()`]
    "UpdatedOn" datetimeoffset [not null, default: `SYSDATETIMEOFFSET()`]
}

Table "dbo"."GenreRelationship" {
    "GenreId" uniqueidentifier [primary key, not null]
    "DependentGenreId" uniqueidentifier [primary key, not null]
    "Name" nvarchar(256) [not null]
    "Description" nvarchar(2048) [null]
    "Order" int [not null]

    Indexes {
        "GenreId" [name: "IX_GenreRelationship_GenreId"]
        "DependentGenreId" [name: "IX_GenreRelationship_DependentGenreId"]
        ("GenreId", "Order") [name: "UIX_GenreRelationship_GenreId_Order", unique]
    }
}

Ref "FK_GenreRelationship_Genre_GenreId" {
    "dbo"."GenreRelationship"."GenreId" > "dbo"."Genre"."Id"
}

Ref "FK_GenreRelationship_Genre_DependentGenreId" {
    "dbo"."GenreRelationship"."DependentGenreId" > "dbo"."Genre"."Id"
}


Table "dbo"."Artist" {
    "Id" uniqueidentifier [primary key, not null, default: `NEWID()`]
    "Name" nvarchar(256) [not null]
    "Description" nvarchar(2048) [null]
    "DisambiguationText" nvarchar(2048) [null]
    "SystemEntity" bit [not null]
    "Enabled" bit [not null]
    "CreatedOn" datetimeoffset [not null, default: `SYSDATETIMEOFFSET()`]
    "UpdatedOn" datetimeoffset [not null, default: `SYSDATETIMEOFFSET()`]
}

Table "dbo"."ArtistRelationship" {
    "ArtistId" uniqueidentifier [primary key, not null]
    "DependentArtistId" uniqueidentifier [primary key, not null]
    "Name" nvarchar(256) [not null]
    "Description" nvarchar(2048) [null]
    "Order" int [not null]

    Indexes {
        "ArtistId" [name: "IX_ArtistRelationship_ArtistId"]
        "DependentArtistId" [name: "IX_ArtistRelationship_DependentArtistId"]
        ("ArtistId", "Order") [name: "UIX_ArtistRelationship_ArtistId_Order", unique]
    }
}

Ref "FK_ArtistRelationship_Artist_ArtistId" {
    "dbo"."ArtistRelationship"."ArtistId" > "dbo"."Artist"."Id"
}

Ref "FK_ArtistRelationship_Artist_DependentArtistId" {
    "dbo"."ArtistRelationship"."DependentArtistId" > "dbo"."Artist"."Id"
}

Table "dbo"."ArtistGenre" {
    "ArtistId" uniqueidentifier [primary key, not null]
    "GenreId" uniqueidentifier [primary key, not null]
    "Order" int [not null]

    Indexes {
        "ArtistId" [name: "IX_ArtistGenre_ArtistId"]
        "GenreId" [name: "IX_ArtistGenre_GenreId"]
        ("ArtistId", "Order") [name: "UIX_ArtistGenre_ArtistId_Order", unique]
    }
}

Ref "FK_ArtistGenre_Artist_ArtistId" {
    "dbo"."ArtistGenre"."ArtistId" > "dbo"."Artist"."Id"
}

Ref "FK_ArtistGenre_Genre_GenreId" {
    "dbo"."ArtistGenre"."GenreId" > "dbo"."Genre"."Id"
}


Table "dbo"."Product" {
    "Id" uniqueidentifier [primary key, not null, default: `NEWID()`]
    "Title" nvarchar(256) [not null]
    "Description" nvarchar(2048) [null]
    "DisambiguationText" nvarchar(2048) [null]
    "ReleasedOn" date [not null]
    "ReleasedOnYearOnly" bit [not null]
    "SystemEntity" bit [not null]
    "Enabled" bit [not null]
    "CreatedOn" datetimeoffset [not null, default: `SYSDATETIMEOFFSET()`]
    "UpdatedOn" datetimeoffset [not null, default: `SYSDATETIMEOFFSET()`]
}

Table "dbo"."ProductRelationship" {
    "ProductId" uniqueidentifier [primary key, not null]
    "DependentProductId" uniqueidentifier [primary key, not null]
    "Name" nvarchar(256) [not null]
    "Description" nvarchar(2048) [null]
    "Order" int [not null]

    Indexes {
        "ProductId" [name: "IX_ProductRelationship_ProductId"]
        "DependentProductId" [name: "IX_ProductRelationship_DependentProductId"]
        ("ProductId", "Order") [name: "UIX_ProductRelationship_ProductId_Order", unique]
    }
}

Ref "FK_ProductRelationship_Product_ProductId" {
    "dbo"."ProductRelationship"."ProductId" > "dbo"."Product"."Id"
}

Ref "FK_ProductRelationship_Product_DependentProductId" {
    "dbo"."ProductRelationship"."DependentProductId" > "dbo"."Product"."Id"
}


Table "dbo"."Work" {
    "Id" uniqueidentifier [primary key, not null, default: `NEWID()`]
    "Title" nvarchar(256) [not null]
    "Description" nvarchar(2048) [null]
    "DisambiguationText" nvarchar(2048) [null]
    "InternationalStandardMusicalWorkCode" nvarchar(32) [null]
    "ReleasedOn" date [not null]
    "ReleasedOnYearOnly" bit [not null]
    "SystemEntity" bit [not null]
    "Enabled" bit [not null]
    "CreatedOn" datetimeoffset [not null, default: `SYSDATETIMEOFFSET()`]
    "UpdatedOn" datetimeoffset [not null, default: `SYSDATETIMEOFFSET()`]

    Indexes {
        "InternationalStandardMusicalWorkCode" [name: "IX_Work_InternationalStandardMusicalWorkCode"]
    }
}

Table "dbo"."WorkRelationship" {
    "WorkId" uniqueidentifier [primary key, not null]
    "DependentWorkId" uniqueidentifier [primary key, not null]
    "Name" nvarchar(256) [not null]
    "Description" nvarchar(2048) [null]
    "Order" int [not null]

    Indexes {
        "WorkId" [name: "IX_WorkRelationship_WorkId"]
        "DependentWorkId" [name: "IX_WorkRelationship_DependentWorkId"]
        ("WorkId", "Order") [name: "UIX_WorkRelationship_WorkId_Order", unique]
    }
}

Ref "FK_WorkRelationship_Work_WorkId" {
    "dbo"."WorkRelationship"."WorkId" > "dbo"."Work"."Id"
}

Ref "FK_WorkRelationship_Work_DependentWorkId" {
    "dbo"."WorkRelationship"."DependentWorkId" > "dbo"."Work"."Id"
}

Table "dbo"."WorkArtist" {
    "WorkId" uniqueidentifier [primary key, not null]
    "ArtistId" uniqueidentifier [primary key, not null]
    "Order" int [not null]

    Indexes {
        "WorkId" [name: "IX_WorkArtist_WorkId"]
        "ArtistId" [name: "IX_WorkArtist_ArtistId"]
        ("WorkId", "Order") [name: "UIX_WorkArtist_WorkId_Order", unique]
    }
}

Ref "FK_WorkArtist_Work_WorkId" {
    "dbo"."WorkArtist"."WorkId" > "dbo"."Work"."Id"
}

Ref "FK_WorkArtist_Artist_ArtistId" {
    "dbo"."WorkArtist"."ArtistId" > "dbo"."Artist"."Id"
}

Table "dbo"."WorkFeaturedArtist" {
    "WorkId" uniqueidentifier [primary key, not null]
    "ArtistId" uniqueidentifier [primary key, not null]
    "Order" int [not null]

    Indexes {
        "WorkId" [name: "IX_WorkFeaturedArtist_WorkId"]
        "ArtistId" [name: "IX_WorkFeaturedArtist_ArtistId"]
        ("WorkId", "Order") [name: "UIX_WorkFeaturedArtist_WorkId_Order", unique]
    }
}

Ref "FK_WorkFeaturedArtist_Work_WorkId" {
    "dbo"."WorkFeaturedArtist"."WorkId" > "dbo"."Work"."Id"
}

Ref "FK_WorkFeaturedArtist_Artist_ArtistId" {
    "dbo"."WorkFeaturedArtist"."ArtistId" > "dbo"."Artist"."Id"
}

Table "dbo"."WorkPerformer" {
    "WorkId" uniqueidentifier [primary key, not null]
    "ArtistId" uniqueidentifier [primary key, not null]
    "Order" int [not null]

    Indexes {
        "WorkId" [name: "IX_WorkPerformer_WorkId"]
        "ArtistId" [name: "IX_WorkPerformer_ArtistId"]
        ("WorkId", "Order") [name: "UIX_WorkPerformer_WorkId_Order", unique]
    }
}

Ref "FK_WorkPerformer_Work_WorkId" {
    "dbo"."WorkPerformer"."WorkId" > "dbo"."Work"."Id"
}

Ref "FK_WorkPerformer_Artist_ArtistId" {
    "dbo"."WorkPerformer"."ArtistId" > "dbo"."Artist"."Id"
}

Table "dbo"."WorkComposer" {
    "WorkId" uniqueidentifier [primary key, not null]
    "ArtistId" uniqueidentifier [primary key, not null]
    "Order" int [not null]

    Indexes {
        "WorkId" [name: "IX_WorkComposer_WorkId"]
        "ArtistId" [name: "IX_WorkComposer_ArtistId"]
        ("WorkId", "Order") [name: "UIX_WorkComposer_WorkId_Order", unique]
    }
}

Ref "FK_WorkComposer_Work_WorkId" {
    "dbo"."WorkComposer"."WorkId" > "dbo"."Work"."Id"
}

Ref "FK_WorkComposer_Artist_ArtistId" {
    "dbo"."WorkComposer"."ArtistId" > "dbo"."Artist"."Id"
}

Table "dbo"."WorkGenre" {
    "WorkId" uniqueidentifier [primary key, not null]
    "GenreId" uniqueidentifier [primary key, not null]
    "Order" int [not null]

    Indexes {
        "WorkId" [name: "IX_WorkGenre_WorkId"]
        "GenreId" [name: "IX_WorkGenre_GenreId"]
        ("WorkId", "Order") [name: "UIX_WorkGenre_WorkId_Order", unique]
    }
}

Ref "FK_WorkGenre_Work_WorkId" {
    "dbo"."WorkGenre"."WorkId" > "dbo"."Work"."Id"
}

Ref "FK_WorkGenre_Genre_GenreId" {
    "dbo"."WorkGenre"."GenreId" > "dbo"."Genre"."Id"
}

Table "dbo"."WorkToProductRelationship" {
    "WorkId" uniqueidentifier [primary key, not null]
    "ProductId" uniqueidentifier [primary key, not null]
    "Name" nvarchar(256) [not null]
    "Description" nvarchar(2048) [null]
    "Order" int [not null]
    "ReferenceOrder" int [not null]

    Indexes {
        "WorkId" [name: "IX_WorkToProductRelationship_WorkId"]
        "ProductId" [name: "IX_WorkToProductRelationship_ProductId"]
        ("WorkId", "Order") [name: "UIX_WorkToProductRelationship_WorkId_Order", unique]
        ("ProductId", "ReferenceOrder") [name: "UIX_WorkToProductRelationship_ProductId_ReferenceOrder", unique]
    }
}

Ref "FK_WorkToProductRelationship_Work_WorkId" {
    "dbo"."WorkToProductRelationship"."WorkId" > "dbo"."Work"."Id"
}

Ref "FK_WorkToProductRelationship_Product_ProductId" {
    "dbo"."WorkToProductRelationship"."ProductId" > "dbo"."Product"."Id"
}


Table "dbo"."ReleaseGroup" {
    "Id" uniqueidentifier [primary key, not null, default: `NEWID()`]
    "Title" nvarchar(256) [not null]
    "Description" nvarchar(2048) [null]
    "DisambiguationText" nvarchar(2048) [null]
    "Enabled" bit [not null]
    "CreatedOn" datetimeoffset [not null, default: `SYSDATETIMEOFFSET()`]
    "UpdatedOn" datetimeoffset [not null, default: `SYSDATETIMEOFFSET()`]
}

Table "dbo"."ReleaseGroupRelationship" {
    "ReleaseGroupId" uniqueidentifier [primary key, not null]
    "DependentReleaseGroupId" uniqueidentifier [primary key, not null]
    "Name" nvarchar(256) [not null]
    "Description" nvarchar(2048) [null]
    "Order" int [not null]

    Indexes {
        "ReleaseGroupId" [name: "IX_ReleaseGroupRelationship_ReleaseGroupId"]
        "DependentReleaseGroupId" [name: "IX_ReleaseGroupRelationship_DependentReleaseGroupId"]
        ("ReleaseGroupId", "Order") [name: "UIX_ReleaseGroupRelationship_ReleaseGroupId_Order", unique]
    }
}

Ref "FK_ReleaseGroupRelationship_ReleaseGroup_ReleaseGroupId" {
    "dbo"."ReleaseGroupRelationship"."ReleaseGroupId" > "dbo"."ReleaseGroup"."Id"
}

Ref "FK_ReleaseGroupRelationship_ReleaseGroup_DependentReleaseGroupId" {
    "dbo"."ReleaseGroupRelationship"."DependentReleaseGroupId" > "dbo"."ReleaseGroup"."Id"
}


Table "dbo"."Release" {
    "Id" uniqueidentifier [primary key, not null, default: `NEWID()`]
    "Title" nvarchar(256) [not null]
    "Description" nvarchar(2048) [null]
    "DisambiguationText" nvarchar(2048) [null]
    "Barcode" nvarchar(32) [null]
    "CatalogNumber" nvarchar(32) [null]
    "MediaFormat" nvarchar(256) [null]
    "PublishFormat" nvarchar(256) [null]
    "ReleasedOn" date [not null]
    "ReleasedOnYearOnly" bit [not null]
    "Enabled" bit [not null]
    "CreatedOn" datetimeoffset [not null, default: `SYSDATETIMEOFFSET()`]
    "UpdatedOn" datetimeoffset [not null, default: `SYSDATETIMEOFFSET()`]

    Indexes {
        "Barcode" [name: "IX_Release_Barcode"]
        "CatalogNumber" [name: "IX_Release_CatalogNumber"]
    }
}
